[build]

base = "website"
publish = "website/public"
command = "curl -sSL -o /tmp/docsite https://github.com/sourcegraph/docsite/releases/download/v1.0.5/docsite_v1.0.5_linux_amd64 && chmod +x /tmp/docsite && (cd .. && /tmp/docsite check) && yarn run prettier && yarn run build"

[build.environment]
  YARN_VERSION = "1.15.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/assets/*"
  to = "https://f155c4ab.ngrok.io/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/community/*"
  to = "https://f155c4ab.ngrok.io/community/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/direction/*"
  to = "https://f155c4ab.ngrok.io/direction/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/company/*"
  to = "https://f155c4ab.ngrok.io/company/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/handbook/*"
  to = "https://f155c4ab.ngrok.io/handbook/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/retrospectives/*"
  to = "https://f155c4ab.ngrok.io/retrospectives/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/search"
  to = "https://f155c4ab.ngrok.io/search"
  status = 200
  force = true
