[build]
  publish = "out"
  command = "pnpm run build"

[build.environment]
# Keep this in sync with package.json "engines".
  NODE_VERSION = "18.9.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/terms/archives/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# ========== SOURCEGRAPH REDIRECTS ==========
[[redirects]]
  from = "/changelog"
  to = "https://sourcegraph.com/docs/CHANGELOG"

[[redirects]]
  from = "/app"
  to = "/cody"
  
[[redirects]]
  from = "/get-cody"
  to = "/cody"

[[redirects]]
  from = "/own"
  to = "https://sourcegraph.com/docs/own"
  status = 301
  force = true
# ========== END SOURCEGRAPH REDIRECTS ==========

# ========== HANDBOOK REDIRECTS ==========
[[redirects]]
  from = "/company"
  to = "https://handbook.sourcegraph.com/#stq=company"

[[redirects]]
  from = "/company/*"
  to = "https://handbook.sourcegraph.com/:splat"

[[redirects]]
  from = "/retrospectives/*"
  to = "https://handbook.sourcegraph.com/company-info-and-process/communication/retrospectives"

[[redirects]]
  from = "/workflow/*"
  to = "https://handbook.sourcegraph.com/#stq=workflow"

[[redirects]]
  from = "/search"
  to = "https://handbook.sourcegraph.com/#stq=:q"
  query = {q = ":q"}

[[redirects]]
  from = "/handbook/*"
  to = "https://handbook.sourcegraph.com/:splat"
# ========== END HANDBOOK REDIRECTS ==========

# ========== LEGAL REDIRECTS ==========
[[redirects]]
  from = "/terms-cloud"
  to = "/terms/cloud"

[[redirects]]
  from = "/terms-dotcom"
  to = "/terms/cloud"

[[redirects]]
  from = "/terms-gov"
  to = "/terms/gov"

[[redirects]]
  from = "/privacy"
  to = "/terms/privacy"

[[redirects]]
  from = "/privacy/cookie-policy"
  to = "/terms/cookie-policy"

[[redirects]]
  from = "/terms-private"
  to = "/terms/self-hosted"

[[redirects]]
  from = "/terms-self-hosted"
  to = "/terms/self-hosted"

[[redirects]]
  from = "/subprocessors"
  to = "/terms/subprocessors"
# ========== END LEGAL REDIRECTS ==========

# ========== BLOG REDIRECTS ==========

[[redirects]]
    from = "/blog/code-intelligence-on-sourcegraph-com"
    to = "/blog"

[[redirects]]
    from = "/blog/a-programmers-guide-to-find-and-replace"
    to = "/blog"

[[redirects]]
    from = "/blog/improving-security-through-transparency"
    to = "/blog"

[[redirects]]
    from = "/blog/universal-code-intelligence-github-sourcegraph-browser-extension"
    to = "/blog"

[[redirects]]
    from = "/blog/universal-code-search-gitlab"
    to = "/blog"

[[redirects]]
    from = "/blog/continuous-delivery-mindset"
    to = "/blog"

[[redirects]]
    from = "/blog/role-of-observability-tools-high-performing-development-teams"
    to = "/blog"

[[redirects]]
    from = "/blog/remote-work-calendar"
    to = "/blog"

[[redirects]]
    from = "/blog/cloud-optimization-part-1-visibility"
    to = "/blog"

[[redirects]]
    from = "/blog/release-anxiety"
    to = "/blog"

[[redirects]]
  from = "/blog/batch-changing-hundreds-of-repositories-at-typeform"
  to = "https://medium.com/typeforms-engineering-blog/saving-dozens-of-engineering-hours-by-batch-changing-hundreds-of-repositories-at-a-time-e4c5a454df2d"

[[redirects]]
  from = "/blog/better-onboarding-advice-from-engineering-leaders"
  to = "/blog/better-onboarding-how-to-prevent-codebase-overwhelm"

[[redirects]]
  from = "/go/:slug"
  to = "/blog/go/:slug"

[[redirects]]
  from = "/go"
  to = "/blog"

[[redirects]]
  from = "/strange-loop/:slug"
  to = "/blog/strange-loop/:slug"

[[redirects]]
  from = "/strange-loop"
  to = "/blog"

[[redirects]]
  from = "/graphql/:slug"
  to = "/blog/graphql/:slug"

[[redirects]]
  from = "/graphql"
  to = "/blog"

[[redirects]]
  from = "/github-universe/:slug"
  to = "/blog/github-universe/:slug"

[[redirects]]
  from = "/github-universe"
  to = "/blog"
# ========== END BLOG REDIRECTS ==========

# ========== INDIVIDUAL REDIRECTS ==========
[[redirects]]
  from = "/contact/sales"
  to = "/contact/request-info"

[[redirects]]
  from = "/contact/product-specialist"
  to = "/contact/request-info"

[[redirects]]
  from = "/contact/request-demo"
  to = "/contact/request-info"

[[redirects]]
  from = "/contact/request-code-change-management-demo"
  to = "/contact/request-info"

[[redirects]]
  from = "/get-started/self-hosted"
  to = "/docs/admin/deploy/docker-single-container"

[[redirects]]
  from = "/customers"
  to = "/use-cases"

[[redirects]]
  from = "/careers"
  to = "/jobs"

[[redirects]]
  from = "/cloud-beta"
  to = "/"

[[redirects]]
  from = "/use-cases/vulnerabilities"
  to = "/use-cases/code-security"

[[redirects]]
  from = "/press-release/*"
  to = "/press/:splat"

[[redirects]]
  from = "/press/big-code-survey-2020"
  to = "/blog/big-code-survey-2020"

[[redirects]]
  from = "/get-started/cloud"
  to = "/docs/admin/deploy"
  force = true

[[redirects]]
  from = "/support"
  to = "/contact"

[[redirects]]
  from = "/cody/pricing"
  to = "/pricing"

[[redirects]]
  from = "/code-search/pricing"
  to = "/pricing"

[[redirects]]
  from = "/cloud"
  to = "/enterprise"

[[redirects]]
  from = "/case-studies/customer-story/casestudycontent"
  to = "/case-studies"

[[redirects]]
  from = "/docs/extensions"
  to = "/docs"

# ========== END INDIVIDUAL REDIRECTS ==========

# ========== WHOLE SITE REDIRECT ==========

[[redirects]]
  from = "https://about.sourcegraph.com/*"
  to = "https://sourcegraph.com/:splat"
  status = 301
  force = true

# ========== END WHOLE SITE REDIRECT ==========
