[build]

base = "website"
publish = "website/public"
command = "curl -sSL -o /tmp/docsite https://github.com/sourcegraph/docsite/releases/download/v1.5.0/docsite_v1.5.0_linux_amd64 && chmod +x /tmp/docsite && (cd .. && /tmp/docsite check) && yarn run build"

[build.environment]
  YARN_VERSION = "1.15.2"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/assets/*"
  to = "https://about-docsite.sourcegraph.com/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/handbook/community"
  to = "https://about-docsite.sourcegraph.com/handbook/community"
  status = 200
  force = true
[[redirects]]
  from = "/handbook/community/*"
  to = "https://about-docsite.sourcegraph.com/handbook/community/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/direction"
  to = "https://about-docsite.sourcegraph.com/handbook/direction"
  status = 200
  force = true
[[redirects]]
  from = "/direction/*"
  to = "https://about-docsite.sourcegraph.com/handbook/direction/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/company"
  to = "https://about-docsite.sourcegraph.com/handbook/company"
  status = 200
  force = true
[[redirects]]
  from = "/company/*"
  to = "https://about-docsite.sourcegraph.com/handbook/company/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/handbook"
  to = "https://about-docsite.sourcegraph.com/handbook"
  status = 200
  force = true
[[redirects]]
  from = "/handbook/*"
  to = "https://about-docsite.sourcegraph.com/handbook/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/retrospectives"
  to = "https://about-docsite.sourcegraph.com/retrospectives"
  status = 200
  force = true
[[redirects]]
  from = "/retrospectives/*"
  to = "https://about-docsite.sourcegraph.com/retrospectives/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/workflow"
  to = "https://about-docsite.sourcegraph.com/workflow"
  status = 200
  force = true
[[redirects]]
  from = "/workflow/*"
  to = "https://about-docsite.sourcegraph.com/workflow/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/search"
  to = "https://about-docsite.sourcegraph.com/search"
  status = 200
  force = true
